name: Support Question
description: Ask for help with setup or usage
title: "[Support] "
labels: ["question", "support"]
body:
  - type: markdown
    attributes:
      value: |
        Need help with ChatBoxAI Docker setup? Please provide as much detail as possible.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: I'm trying to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does your question fall into?
      options:
        - Installation/Setup
        - Docker Configuration
        - Wayland Integration
        - Multi-Architecture Build
        - Performance Issues
        - Other
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already attempted?
      placeholder: I tried following the README but...

  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      description: Output of `docker --version`
      placeholder: "Docker version 24.0.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version
      placeholder: "Ubuntu 22.04"

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - x86_64 (AMD64)
        - ARM64
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any error messages or log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Anything else that might be relevant